// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal_api.proto

package authority

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthToken struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=authToken,proto3" json:"authToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthToken) Reset()         { *m = AuthToken{} }
func (m *AuthToken) String() string { return proto.CompactTextString(m) }
func (*AuthToken) ProtoMessage()    {}
func (*AuthToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_927ea7049a2d0eaa, []int{0}
}

func (m *AuthToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthToken.Unmarshal(m, b)
}
func (m *AuthToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthToken.Marshal(b, m, deterministic)
}
func (m *AuthToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthToken.Merge(m, src)
}
func (m *AuthToken) XXX_Size() int {
	return xxx_messageInfo_AuthToken.Size(m)
}
func (m *AuthToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthToken.DiscardUnknown(m)
}

var xxx_messageInfo_AuthToken proto.InternalMessageInfo

func (m *AuthToken) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_927ea7049a2d0eaa, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Error struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=isOk,proto3" json:"isOk,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_927ea7049a2d0eaa, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UserProps struct {
	// Types that are valid to be assigned to User:
	//	*UserProps_Id
	//	*UserProps_AuthToken
	User                 isUserProps_User  `protobuf_oneof:"user"`
	Props                []*UserProps_Prop `protobuf:"bytes,5,rep,name=props,proto3" json:"props,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UserProps) Reset()         { *m = UserProps{} }
func (m *UserProps) String() string { return proto.CompactTextString(m) }
func (*UserProps) ProtoMessage()    {}
func (*UserProps) Descriptor() ([]byte, []int) {
	return fileDescriptor_927ea7049a2d0eaa, []int{3}
}

func (m *UserProps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProps.Unmarshal(m, b)
}
func (m *UserProps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProps.Marshal(b, m, deterministic)
}
func (m *UserProps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProps.Merge(m, src)
}
func (m *UserProps) XXX_Size() int {
	return xxx_messageInfo_UserProps.Size(m)
}
func (m *UserProps) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProps.DiscardUnknown(m)
}

var xxx_messageInfo_UserProps proto.InternalMessageInfo

type isUserProps_User interface {
	isUserProps_User()
}

type UserProps_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type UserProps_AuthToken struct {
	AuthToken string `protobuf:"bytes,2,opt,name=authToken,proto3,oneof"`
}

func (*UserProps_Id) isUserProps_User() {}

func (*UserProps_AuthToken) isUserProps_User() {}

func (m *UserProps) GetUser() isUserProps_User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserProps) GetId() string {
	if x, ok := m.GetUser().(*UserProps_Id); ok {
		return x.Id
	}
	return ""
}

func (m *UserProps) GetAuthToken() string {
	if x, ok := m.GetUser().(*UserProps_AuthToken); ok {
		return x.AuthToken
	}
	return ""
}

func (m *UserProps) GetProps() []*UserProps_Prop {
	if m != nil {
		return m.Props
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UserProps) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UserProps_Id)(nil),
		(*UserProps_AuthToken)(nil),
	}
}

type UserProps_Prop struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProps_Prop) Reset()         { *m = UserProps_Prop{} }
func (m *UserProps_Prop) String() string { return proto.CompactTextString(m) }
func (*UserProps_Prop) ProtoMessage()    {}
func (*UserProps_Prop) Descriptor() ([]byte, []int) {
	return fileDescriptor_927ea7049a2d0eaa, []int{3, 0}
}

func (m *UserProps_Prop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProps_Prop.Unmarshal(m, b)
}
func (m *UserProps_Prop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProps_Prop.Marshal(b, m, deterministic)
}
func (m *UserProps_Prop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProps_Prop.Merge(m, src)
}
func (m *UserProps_Prop) XXX_Size() int {
	return xxx_messageInfo_UserProps_Prop.Size(m)
}
func (m *UserProps_Prop) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProps_Prop.DiscardUnknown(m)
}

var xxx_messageInfo_UserProps_Prop proto.InternalMessageInfo

func (m *UserProps_Prop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserProps_Prop) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthToken)(nil), "internal_api.AuthToken")
	proto.RegisterType((*User)(nil), "internal_api.User")
	proto.RegisterType((*Error)(nil), "internal_api.Error")
	proto.RegisterType((*UserProps)(nil), "internal_api.UserProps")
	proto.RegisterType((*UserProps_Prop)(nil), "internal_api.UserProps.Prop")
}

func init() { proto.RegisterFile("internal_api.proto", fileDescriptor_927ea7049a2d0eaa) }

var fileDescriptor_927ea7049a2d0eaa = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x6c, 0xbe, 0x8a, 0x79, 0x2d, 0x52, 0x9e, 0x42, 0x43, 0x28, 0x52, 0xf6, 0x54, 0x0f, 0x06,
	0x89, 0x77, 0xb1, 0x15, 0xd1, 0x9e, 0x2c, 0x51, 0xcf, 0xb2, 0xd2, 0x45, 0x97, 0xe6, 0x8b, 0xdd,
	0x44, 0xf0, 0x6f, 0xf8, 0x37, 0xfc, 0x93, 0xb2, 0x9b, 0x34, 0xdb, 0x20, 0x5e, 0xc2, 0x7b, 0x33,
	0xc9, 0xcc, 0xbc, 0x09, 0x20, 0xcf, 0x2b, 0x26, 0x72, 0x9a, 0xbe, 0xd2, 0x92, 0x47, 0xa5, 0x28,
	0xaa, 0x02, 0xc7, 0x87, 0x18, 0x39, 0x07, 0x7f, 0x59, 0x57, 0x1f, 0xcf, 0xc5, 0x8e, 0xe5, 0x38,
	0x03, 0x9f, 0xee, 0x97, 0xc0, 0x9a, 0x5b, 0x0b, 0x3f, 0x31, 0x00, 0xb9, 0x01, 0xf7, 0x45, 0x32,
	0x81, 0xc7, 0x60, 0xf3, 0x6d, 0x4b, 0xdb, 0x7c, 0x8b, 0xa7, 0xe0, 0xb1, 0x8c, 0xf2, 0x34, 0xb0,
	0x35, 0xd4, 0x2c, 0x88, 0xe0, 0xe6, 0x34, 0x63, 0x81, 0xa3, 0x41, 0x3d, 0x93, 0x0b, 0xf0, 0xee,
	0x84, 0x28, 0x84, 0x22, 0xb9, 0x7c, 0xdc, 0x69, 0x91, 0xa3, 0x44, 0xcf, 0x38, 0x01, 0x27, 0x93,
	0xef, 0xad, 0x88, 0x1a, 0xc9, 0x8f, 0x05, 0xbe, 0x72, 0xdc, 0x88, 0xa2, 0x94, 0x38, 0x31, 0xb6,
	0x0f, 0x03, 0x6d, 0x7c, 0x76, 0x18, 0xd7, 0x6e, 0x09, 0x03, 0x61, 0x0c, 0x5e, 0xa9, 0x3e, 0x0d,
	0xbc, 0xb9, 0xb3, 0x18, 0xc5, 0xb3, 0xa8, 0xd7, 0x46, 0xa7, 0x1c, 0xa9, 0x67, 0xd2, 0xbc, 0x1a,
	0x5e, 0x82, 0xab, 0xd6, 0x2e, 0xbe, 0x65, 0xe2, 0xab, 0x43, 0x3f, 0x69, 0x5a, 0xb3, 0xfd, 0xa1,
	0x7a, 0x59, 0x0d, 0xc1, 0xad, 0x25, 0x13, 0xf1, 0xb7, 0x05, 0xa3, 0x75, 0x6b, 0xb0, 0xdc, 0xac,
	0xf1, 0x16, 0xf0, 0x9e, 0x55, 0xca, 0x65, 0xf5, 0x65, 0x2a, 0x9e, 0xf6, 0x43, 0x74, 0x44, 0x88,
	0x7f, 0xd3, 0x91, 0x01, 0x5e, 0xc3, 0xf8, 0xa9, 0x11, 0x69, 0x4a, 0x98, 0xfe, 0x73, 0x43, 0x78,
	0xd2, 0x27, 0x74, 0xcd, 0x64, 0xf0, 0x36, 0xd4, 0xff, 0xfc, 0xea, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x6c, 0xfc, 0xea, 0xd7, 0x09, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InternalAPIClient is the client API for InternalAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InternalAPIClient interface {
	GetUserByAuthToken(ctx context.Context, in *AuthToken, opts ...grpc.CallOption) (*User, error)
	SetUserProps(ctx context.Context, in *UserProps, opts ...grpc.CallOption) (*Error, error)
}

type internalAPIClient struct {
	cc *grpc.ClientConn
}

func NewInternalAPIClient(cc *grpc.ClientConn) InternalAPIClient {
	return &internalAPIClient{cc}
}

func (c *internalAPIClient) GetUserByAuthToken(ctx context.Context, in *AuthToken, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/internal_api.InternalAPI/GetUserByAuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAPIClient) SetUserProps(ctx context.Context, in *UserProps, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/internal_api.InternalAPI/SetUserProps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalAPIServer is the server API for InternalAPI service.
type InternalAPIServer interface {
	GetUserByAuthToken(context.Context, *AuthToken) (*User, error)
	SetUserProps(context.Context, *UserProps) (*Error, error)
}

// UnimplementedInternalAPIServer can be embedded to have forward compatible implementations.
type UnimplementedInternalAPIServer struct {
}

func (*UnimplementedInternalAPIServer) GetUserByAuthToken(ctx context.Context, req *AuthToken) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByAuthToken not implemented")
}
func (*UnimplementedInternalAPIServer) SetUserProps(ctx context.Context, req *UserProps) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserProps not implemented")
}

func RegisterInternalAPIServer(s *grpc.Server, srv InternalAPIServer) {
	s.RegisterService(&_InternalAPI_serviceDesc, srv)
}

func _InternalAPI_GetUserByAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAPIServer).GetUserByAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal_api.InternalAPI/GetUserByAuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAPIServer).GetUserByAuthToken(ctx, req.(*AuthToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAPI_SetUserProps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProps)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAPIServer).SetUserProps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal_api.InternalAPI/SetUserProps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAPIServer).SetUserProps(ctx, req.(*UserProps))
	}
	return interceptor(ctx, in, info, handler)
}

var _InternalAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "internal_api.InternalAPI",
	HandlerType: (*InternalAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByAuthToken",
			Handler:    _InternalAPI_GetUserByAuthToken_Handler,
		},
		{
			MethodName: "SetUserProps",
			Handler:    _InternalAPI_SetUserProps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal_api.proto",
}
